spring.application.name=eventify

# Configuracion de la aplicacion
server.port=8080

# Configuracion de seeders (desactivado por defecto para cumplir criterio de aceptacion 3)
app.seed.enabled=false

# Configuracion de logging
logging.level.com.riwi.eventify=INFO

# Configuracion de base de datos H2
spring.datasource.url=jdbc:h2:file:./data/eventify
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracion de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion de consola H2 (opcional, para desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
