spring.application.name=eventify

# Configuracion de la aplicacion
server.port=8080

# Configuracion de seeders (desactivado por defecto para cumplir criterio de aceptacion 3)
app.seed.enabled=false

# Configuracion de logging
logging.level.com.riwi.eventify=INFO
