package com.riwi.talent.model;

import java.time.LocalDateTime;

/**
 * Employee entity representing a coder/developer in the system.
 * This record provides immutable data transfer for database operations.
 * 
 * @param id Employee unique identifier
 * @param name Employee full name
 * @param email Employee email address
 * @param department Department where the employee works
 * @param salary Employee salary
 * @param hireDate Date when employee was hired
 * @param active Whether the employee is currently active
 */
public record Employee(
    Long id,
    String name,
    String email,
    String department,
    Double salary,
    LocalDateTime hireDate,
    Boolean active
) {
    /**
     * Compact constructor for validation
     */
    public Employee {
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Employee name cannot be null or empty");
        }
        if (email == null || !email.contains("@")) {
            throw new IllegalArgumentException("Valid email is required");
        }
        if (department == null || department.trim().isEmpty()) {
            throw new IllegalArgumentException("Department cannot be null or empty");
        }
        if (salary != null && salary < 0) {
            throw new IllegalArgumentException("Salary cannot be negative");
        }
    }
    
    /**
     * Factory method for creating new employees (auto-generates ID and hire date)
     */
    public static Employee createNew(String name, String email, String department, Double salary) {
        return new Employee(
            null, // ID will be generated by database
            name,
            email,
            department,
            salary,
            LocalDateTime.now(),
            true
        );
    }
    
    /**
     * Factory method for creating employee from database result
     */
    public static Employee fromDatabase(Long id, String name, String email, 
                                      String department, Double salary, 
                                      LocalDateTime hireDate, Boolean active) {
        return new Employee(id, name, email, department, salary, hireDate, active);
    }
}
